version: '3'
services:
  lo_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
    #command: "gunicorn -w 4 -b 0.0.0.0:8000 app:app"
    #command: "supervisord -c  /etc/supervisord.conf"
    #command: "sleep 100000"
    command: bash -c "gunicorn -D -w 4 -b 0.0.0.0:8000 app:app;/app/docker/office.sh"
